database_path: STOCH_DTB_NH3_PYRO_EMST/dtb_nh3_pyro_emst_resampled
model_name_suffix: NH3_PYRO_EMST_RESAMPLED_1
new_model_folder: true
networks_types:
- MLP
- MLP
networks_def:
- cluster0
- cluster1
clusters:
  cluster0:
    nb_units_in_layers_list:
    - 200
    - 150
    layers_activation_list:
    - GeLu
    - GeLu
    - Id
    layers_type:
    - dense
    - dense
    - dense
  cluster1:
    nb_units_in_layers_list:
    - 200
    - 150
    layers_activation_list:
    - GeLu
    - GeLu
    - Id
    layers_type:
    - dense
    - dense
    - dense  
learning:
  optimizer: adam
  loss: MSE
  scheduler_option: ExpLR
  decay_rate: 0.999
  initial_learning_rate: 0.001
  batch_size: 2048
  epochs_list:
  - 1000
  - 1000
  val_every: 20
