database_path: STOCH_DTB_H2_POF_2023/dtb_resampled
model_name_suffix: H2_POF_2023
new_model_folder: true
networks_types:
- MLP
- MLP
networks_def:
- cluster0
- cluster1
clusters:
  cluster0:
    nb_units_in_layers_list:
    - 20
    - 20
    layers_activation_list:
    - tanh
    - tanh
    - Id
    layers_type:
    - dense
    - dense
    - dense
  cluster1:
    nb_units_in_layers_list:
    - 40
    - 40
    layers_activation_list:
    - tanh
    - tanh
    - Id
    layers_type:
    - dense
    - dense
    - dense
learning:
  initial_learning_rate: 0.001
  batch_size: 2048
  epochs_list:
  - 500
  - 500
  decay_rate: 0.9991
